// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJVyxUduwSAGYcZz_EdFwhPDgnoCaMsE',
    appId: '1:788089822817:web:c25d04d2f38b7d878a9420',
    messagingSenderId: '788089822817',
    projectId: 'taskmanger-98138',
    authDomain: 'taskmanger-98138.firebaseapp.com',
    storageBucket: 'taskmanger-98138.firebasestorage.app',
    measurementId: 'G-W23R1N46BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtl5NfmV-WiYllPvQCBE6rY-PCODOQQRM',
    appId: '1:788089822817:android:7ef6c00702a8bc228a9420',
    messagingSenderId: '788089822817',
    projectId: 'taskmanger-98138',
    storageBucket: 'taskmanger-98138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRI6fJOmPw_sRRMpmsUPB0J1aYizoNds',
    appId: '1:788089822817:ios:be242c8017960ff38a9420',
    messagingSenderId: '788089822817',
    projectId: 'taskmanger-98138',
    storageBucket: 'taskmanger-98138.firebasestorage.app',
    iosBundleId: 'com.example.chatGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJVyxUduwSAGYcZz_EdFwhPDgnoCaMsE',
    appId: '1:788089822817:web:d27f0f3ff82338788a9420',
    messagingSenderId: '788089822817',
    projectId: 'taskmanger-98138',
    authDomain: 'taskmanger-98138.firebaseapp.com',
    storageBucket: 'taskmanger-98138.firebasestorage.app',
    measurementId: 'G-XN7QVPBDHB',
  );
}
